"use client";
import {useState} from "react";
type Status="RUNNING"|"EXPERIMENT"|"WAITING"|"ERROR"|"COMPLETED";
const initial=[{id:"AG-01",name:"Supervisor",role:"Orchestrator",status:"RUNNING" as Status,progress:72},{id:"AG-02",name:"Builder",role:"Engineering",status:"EXPERIMENT" as Status,progress:48},{id:"AG-03",name:"Guardian",role:"Security",status:"WAITING" as Status,progress:0}];
const events=["Control Center gestartet","Sandbox #01 bereitgestellt","Builder: Experiment 04 gestartet","Guardian: Capability Check wartet","Task T-104 läuft"];
function Badge({s}:{s:Status}){return <span className={"badge "+s.toLowerCase()}><i/> {s}</span>}
export default function Home(){const [agents,setAgents]=useState(initial);const [locked,setLocked]=useState(false);const [eventsList,setEvents]=useState(events);const run=()=>{setAgents(a=>a.map(x=>x.id==="AG-03"?{...x,status:"RUNNING",progress:18}:x));setEvents(e=>["Guardian aktiviert — Capability Check läuft",...e]);};return <main className="shell">
<aside><div className="brand"><span>✦</span><div><b>BabajagaBoB</b><small>CONTROL CENTER</small></div></div><nav>{["Overview","Agents","Missions","Experiments","Sandboxes","Tests","Deployments","Artifacts","Security","Integrations"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}<span>{i===0?"●":""}</span></button>)}</nav><div className="sideStatus"><small>SYSTEM</small><Badge s={locked?"ERROR":"RUNNING"}/><p>{locked?"EMERGENCY LOCKDOWN":"Operational · local state"}</p></div></aside>
<section className="content"><header><div><small>PROJECT / BABAJAGABOB</small><h1>Control Center</h1></div><div className="headerActions"><span className="privacy">NETWORK · DENY BY DEFAULT</span><button onClick={()=>setLocked(!locked)} className={locked?"danger":"lock"}>{locked?"UNLOCK":"EMERGENCY LOCKDOWN"}</button></div></header>
{locked&&<div className="alert">Emergency lockdown active — execution is halted until explicitly released.</div>}
<div className="metrics">{[["Agents","03","2 active"],["Tasks","07","1 running"],["Experiments","04","1 active"],["Sandboxes","03","all isolated"]].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div>
<div className="grid"><section className="panel wide"><div className="panelHead"><div><small>LIVE OBSERVATORY</small><h2>Agent Activity</h2></div><span className="live">● LIVE</span></div><div className="agents">{agents.map(a=><div className="agent" key={a.id}><div className="avatar">{a.name[0]}</div><div className="agentMain"><div className="agentTitle"><b>{a.name}</b><span>{a.role}</span><Badge s={a.status}/></div><div className="bar"><i style={{width:a.progress+"%"}}/></div><small>{a.id} · {a.progress}% progress</small></div></div>)}</div></section>
<section className="panel"><div className="panelHead"><div><small>EXECUTION</small><h2>Mission Queue</h2></div></div><div className="task"><b>T-104</b><span>Build GUI foundation</span><Badge s="RUNNING"/></div><div className="task"><b>T-105</b><span>Validate capability model</span><Badge s="WAITING"/></div><div className="task"><b>T-106</b><span>Regression harness</span><Badge s="COMPLETED"/></div></section>
<section className="panel"><div className="panelHead"><div><small>CONTROLLED RUNS</small><h2>Experiments</h2></div></div><div className="experiment"><div><b>EXP-004</b><span>UI state transition</span></div><Badge s="EXPERIMENT"/><div className="miniBar"><i style={{width:"48%"}}/></div><small>48% · sandbox-03</small></div><div className="experiment"><div><b>EXP-003</b><span>Recovery rehearsal</span></div><Badge s="COMPLETED"/><small>validated · rollback ready</small></div></section>
<section className="panel wide"><div className="panelHead"><div><small>EVENT FABRIC</small><h2>Live Activity</h2></div><button onClick={run}>Run Guardian Check</button></div><div className="timeline">{eventsList.slice(0,6).map((e,i)=><div className="event" key={i}><i/><span>{e}</span><small>{i<2?"now":i*2+"m ago"}</small></div>)}</div></section></div>
<footer><span>LOCAL CONTROL PLANE</span><span>Audit: ON</span><span>Secrets: BROKERED</span><span>External sharing: DISABLED</span></footer></section></main>}