"use client";
import {useEffect,useState} from "react";import type {Agent,Event,Experiment,Mission,Sandbox,Status} from "../lib/types";import {StatusBadge} from "./status-badge";
const nav=["Overview","Agents","Missions","Tasks","Queue","Approvals","Experiments","Sandboxes","Tests","Deployments","Artifacts","Security","Integrations","Devices","Knowledge","Simulation"];
type Snapshot={agents:Agent[];missions:Mission[];tasks:{id:string;title:string;status:Status;progress:number;risk:string;assignedAgent:string;requiresApproval:boolean}[];experiments:Experiment[];sandboxes:Sandbox[];events:Event[];approvals:{id:string;taskId:string;status:string;reason:string}[];locked:boolean};
export default function ControlCenter(){
 const [section,setSection]=useState("Overview"),[data,setData]=useState<Snapshot|null>(null),[queue,setQueue]=useState<{id:string;taskId:string;agentId:string;state:string;attempt:number;maxAttempts:number;risk:string}[]>([]),[tools,setTools]=useState<{id:string;version:string;name:string;risk:string;network:string}[]>([]),[capabilities,setCapabilities]=useState<{edges:unknown[];tokens:unknown[]}|null>(null),[artifacts,setArtifacts]=useState<{id:string;name:string;kind:string;taskId:string;runId:string;sandboxId:string;agentId:string;knowledgeState:string;digest:string}[]>([]),[error,setError]=useState("");
 const load=async()=>{try{const r=await fetch("/api/control",{cache:"no-store"});if(!r.ok)throw new Error("Control Plane unavailable");setData(await r.json());const q=await fetch("/api/queue",{cache:"no-store"});if(q.ok)setQueue((await q.json()).jobs);const tr=await fetch("/api/tools",{cache:"no-store"});if(tr.ok)setTools((await tr.json()).tools);const cr=await fetch("/api/capabilities",{cache:"no-store"});if(cr.ok)setCapabilities(await cr.json());const ar=await fetch("/api/artifacts",{cache:"no-store"});if(ar.ok)setArtifacts((await ar.json()).artifacts);setError("")}catch(e){setError(e instanceof Error?e.message:"Unknown error")}};
 useEffect(()=>{load();const id=setInterval(load,2500);return()=>clearInterval(id)},[]);
 const action=async(body:object)=>{if(data?.locked&&"action" in body&&body.action!=="lockdown")return;await fetch("/api/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await load()};
 const locked=Boolean(data?.locked),agents=data?.agents??[],missions=data?.missions??[],tasks=data?.tasks??[],experiments=data?.experiments??[],sandboxes=data?.sandboxes??[],events=data?.events??[],approvals=data?.approvals??[];
 const title=section==="Overview"?"Control Center":section;
 return <main className="shell"><aside><div className="brand"><span>✦</span><div><b>BabajagaBoB</b><small>CONTROL CENTER</small></div></div><nav>{nav.map(x=><button key={x} onClick={()=>setSection(x)} className={section===x?"active":""}>{x}<span>›</span></button>)}</nav><div className="sideStatus"><small>SYSTEM</small><StatusBadge status={locked?"ERROR":"RUNNING"}/><p>{locked?"EMERGENCY LOCKDOWN":"Operational · control plane"}</p></div></aside>
 <section className="content"><header><div><small>PROJECT / BABAJAGABOB</small><h1>{title}</h1></div><div className="headerActions"><span className="privacy">NETWORK · DENY BY DEFAULT</span><button onClick={()=>action({action:"lockdown",locked:!locked})} className="danger">{locked?"RELEASE LOCKDOWN":"EMERGENCY LOCKDOWN"}</button></div></header>
 {error&&<div className="alert">Control Plane error: {error}</div>}{locked&&<div className="alert">Emergency lockdown active — execution is halted until explicitly released.</div>}
 {section==="Overview"?<><div className="metrics">{[{k:"Agents",v:String(agents.length).padStart(2,"0"),s:agents.filter(a=>a.status==="RUNNING"||a.status==="EXECUTING").length+" active"},{k:"Progress",v:String(Math.round(([...agents,...tasks,...experiments].reduce((n,x)=>n+x.progress,0)/Math.max(1,[...agents,...tasks,...experiments].length)))+"%",s:"live work"}},{k:"Tasks",v:String(tasks.length).padStart(2,"0"),s:tasks.filter(t=>t.status==="RUNNING").length+" running"},{k:"Experiments",v:String(experiments.length).padStart(2,"0"),s:experiments.filter(x=>x.status==="EXPERIMENT").length+" active"},{k:"Sandboxes",v:String(sandboxes.length).padStart(2,"0"),s:"isolated"}].map(x=><div className="metric" key={x.k}><small>{x.k}</small><strong>{x.v}</strong><span>{x.s}</span></div>)}</div>
 <div className="grid"><section className="panel"><div className="panelHead"><div><small>LIVE OBSERVATORY</small><h2>Agents</h2></div><span className="live">● LIVE</span></div>{agents.map(a=><div className="agent" key={a.id}><div className="avatar">{a.name[0]}</div><div className="agentMain"><div className="agentTitle"><b>{a.name}</b><span>{a.role}</span><StatusBadge status={a.status}/></div><div className="bar"><i style={{width:a.progress+"%"}}/></div><small>{a.id} · {a.task} · {a.progress}%</small></div></div>)}</section>
 <section className="panel"><div className="panelHead"><div><small>EXECUTION</small><h2>Mission Queue</h2></div></div>{missions.map(m=><div className="task" key={m.id}><b>{m.id}</b><span>{m.title}</span><StatusBadge status={m.status}/></div>)}</section>
 <section className="panel"><div className="panelHead"><div><small>CONTROLLED RUNS</small><h2>Experiments</h2></div></div>{experiments.map(x=><div className="experiment" key={x.id}><div><b>{x.id}</b><span>{x.title}</span><StatusBadge status={x.status}/></div><div className="miniBar"><i style={{width:x.progress+"%"}}/></div><small>{x.progress}% · {x.sandbox}</small></div>)}</section>
 <section className="panel"><div className="panelHead"><div><small>EVENT FABRIC</small><h2>Live Activity</h2></div><button onClick={()=>action({action:"guardian"})} disabled={locked}>Run Guardian Check</button></div><div className="timeline">{events.slice(0,8).map(e=><div className="event" key={e.id}><i/><span>{e.message}</span><small>{e.time}</small></div>)}</div></section></div></>:<section className="panel sectionPanel"><small>MODULE</small><h2>{section}</h2><p>Control-plane module with explicit runtime state. External systems are never presented as connected without an actual integration.</p><div className="moduleGrid">{section==="Agents"?agents.map(x=><Card key={x.id} title={x.name} meta={x.role} status={x.status} detail={x.task}/>):section==="Missions"?missions.map(x=><Card key={x.id} title={x.id} meta={x.owner} status={x.status} detail={x.title+" · "+x.progress+"%"}/>):section==="Experiments"?experiments.map(x=><Card key={x.id} title={x.id} meta={x.sandbox} status={x.status} detail={x.title+" · "+x.progress+"%"}/>):section==="Sandboxes"?sandboxes.map(x=><Card key={x.id} title={x.id} meta={x.type} status={x.status} detail={"Network: "+x.network+" · "+x.task}/>):nav.slice(0,5).map((x,i)=><Card key={x} title={x} meta="Control plane module" status={i===0?"RUNNING":i===1?"WAITING":"QUEUED"} detail="Runtime integration boundary ready")}</div></section>}
 <footer><span>LOCAL CONTROL PLANE</span><span>Audit: ON</span><span>Secrets: BROKERED</span><span>External sharing: DISABLED</span><span>API: LIVE</span></footer></section></main>
}
function Card({title,meta,status,detail}:{title:string;meta:string;status:Status;detail:string}){return <div className="moduleCard"><b>{title}</b><span>{meta}</span><StatusBadge status={status}/><small>{detail}</small></div>}
