"use client";
import {useMemo,useState} from "react"; import type {Agent,Event,Experiment,Mission,Sandbox,Status} from "../lib/types"; import {StatusBadge} from "./status-badge";
const agents:Agent[]=[{id:"AG-01",name:"Supervisor",role:"Orchestrator",status:"RUNNING",progress:72,task:"Coordinating T-104"},{id:"AG-02",name:"Builder",role:"Engineering",status:"EXPERIMENT",progress:48,task:"GUI state experiment"},{id:"AG-03",name:"Guardian",role:"Security",status:"WAITING",progress:0,task:"Capability validation"}];
const missions:Mission[]=[{id:"T-104",title:"Build GUI foundation",status:"RUNNING",progress:72,owner:"Builder"},{id:"T-105",title:"Validate capability model",status:"WAITING",progress:20,owner:"Guardian"},{id:"T-106",title:"Regression harness",status:"COMPLETED",progress:100,owner:"QA"}];
const experiments:Experiment[]=[{id:"EXP-004",title:"UI state transition",status:"EXPERIMENT",progress:48,sandbox:"SB-03"},{id:"EXP-003",title:"Recovery rehearsal",status:"COMPLETED",progress:100,sandbox:"SB-02"}];
const sandboxes:Sandbox[]=[{id:"SB-01",type:"development",status:"RUNNING",network:"DENY",task:"GUI foundation"},{id:"SB-02",type:"recovery",status:"COMPLETED",network:"DENY",task:"Rollback rehearsal"},{id:"SB-03",type:"experiment",status:"EXPERIMENT",network:"ALLOWLIST",task:"UI transition"}];
const nav=["Overview","Agents","Missions","Experiments","Sandboxes","Tests","Deployments","Artifacts","Security","Integrations"];
export default function ControlCenter(){const [section,setSection]=useState("Overview");const [locked,setLocked]=useState(false);const [agentState,setAgentState]=useState(agents);const [events,setEvents]=useState<Event[]>([{id:"1",message:"Control Center gestartet",status:"RUNNING",time:"now"},{id:"2",message:"Sandbox SB-01 bereitgestellt",status:"COMPLETED",time:"1m ago"},{id:"3",message:"Builder: Experiment 04 gestartet",status:"EXPERIMENT",time:"2m ago"},{id:"4",message:"Guardian: Capability Check wartet",status:"WAITING",time:"4m ago"}]);
const runGuardian=()=>{if(locked)return;setAgentState(a=>a.map(x=>x.id==="AG-03"?{...x,status:"RUNNING",progress:18}:x));setEvents(e=>[{id:crypto.randomUUID(),message:"Guardian aktiviert — Capability Check läuft",status:"RUNNING",time:"now"},...e]);};
const title=section==="Overview"?"Control Center":section; const metrics=useMemo(()=>[{k:"Agents",v:"03",s:"2 active"},{k:"Tasks",v:"07",s:"1 running"},{k:"Experiments",v:"04",s:"1 active"},{k:"Sandboxes",v:"03",s:"isolated"}],[section]);
return <main className="shell"><aside><div className="brand"><span>✦</span><div><b>BabajagaBoB</b><small>CONTROL CENTER</small></div></div><nav>{nav.map(x=><button key={x} onClick={()=>setSection(x)} className={section===x?"active":""}>{x}</button>)}</nav><div className="sideStatus"><small>SYSTEM</small><StatusBadge status={locked?"ERROR":"RUNNING"}/><p>{locked?"EMERGENCY LOCKDOWN":"Operational · local state"}</p></div></aside>
<section className="content"><header><div><small>PROJECT / BABAJAGABOB</small><h1>{title}</h1></div><div className="headerActions"><span className="privacy">NETWORK · DENY BY DEFAULT</span><button onClick={()=>setLocked(x=>!x)} className="danger">{locked?"UNLOCK":"EMERGENCY LOCKDOWN"}</button></div></header>
{locked&&<div className="alert">Emergency lockdown active — execution is halted until explicitly released.</div>}
{section==="Overview"?<><div className="metrics">{metrics.map(x=><div className="metric" key={x.k}><small>{x.k}</small><strong>{x.v}</strong><span>{x.s}</span></div>)}</div><div className="grid"><section className="panel"><div className="panelHead"><div><small>LIVE OBSERVATORY</small><h2>Agents</h2></div><span className="live">● LIVE</span></div>{agentState.map(a=><div className="agent" key={a.id}><div className="avatar">{a.name[0]}</div><div className="agentMain"><div className="agentTitle"><b>{a.name}</b><span>{a.role}</span><StatusBadge status={a.status}/></div><div className="bar"><i style={{width:a.progress+"%"}}/></div><small>{a.id} · {a.task} · {a.progress}%</small></div></div>)}</section>
<section className="panel"><div className="panelHead"><div><small>EXECUTION</small><h2>Mission Queue</h2></div></div>{missions.map(m=><div className="task" key={m.id}><b>{m.id}</b><span>{m.title}</span><StatusBadge status={m.status}/></div>)}</section>
<section className="panel"><div className="panelHead"><div><small>CONTROLLED RUNS</small><h2>Experiments</h2></div></div>{experiments.map(x=><div className="experiment" key={x.id}><div><b>{x.id}</b><span>{x.title}</span><StatusBadge status={x.status}/></div><div className="miniBar"><i style={{width:x.progress+"%"}}/></div><small>{x.progress}% · {x.sandbox}</small></div>)}</section>
<section className="panel"><div className="panelHead"><div><small>EVENT FABRIC</small><h2>Live Activity</h2></div><button onClick={runGuardian}>Run Guardian Check</button></div><div className="timeline">{events.slice(0,7).map(e=><div className="event" key={e.id}><i/><span>{e.message}</span><small>{e.time}</small></div>)}</div></section></div></>:<section className="panel sectionPanel"><small>MODULE</small><h2>{section}</h2><p>This module is wired into the active Control Center shell. Its runtime state is explicit; unconnected external systems are never presented as connected.</p><div className="moduleGrid">{section==="Sandboxes"?sandboxes.map(s=><div className="moduleCard" key={s.id}><b>{s.id}</b><span>{s.type}</span><StatusBadge status={s.status}/><small>Network: {s.network} · {s.task}</small></div>):nav.slice(0,5).map((x,i)=><div className="moduleCard" key={x}><b>{x}</b><span>Control plane module</span><StatusBadge status={i===0?"RUNNING":i===1?"WAITING":"QUEUED"}/><small>Ready for runtime integration</small></div>)}</div></section>}
<footer><span>LOCAL CONTROL PLANE</span><span>Audit: ON</span><span>Secrets: BROKERED</span><span>External sharing: DISABLED</span></footer></section></main>}