"use client";
import {useEffect,useState} from "react";
import type {Agent,Event,Experiment,Mission,Sandbox,Status} from "../lib/types";
import {StatusBadge} from "./status-badge";

const nav=["Overview","Agents","Missions","Tasks","Queue","Approvals","Experiments","Sandboxes","Tests","Deployments","Artifacts","Security","Integrations","Devices","Knowledge","Simulation","Replay"];
type Snapshot={agents:Agent[];missions:Mission[];tasks:{id:string;title:string;status:Status;progress:number;risk:string;assignedAgent:string;requiresApproval:boolean}[];experiments:Experiment[];sandboxes:Sandbox[];events:Event[];approvals:{id:string;taskId:string;status:string;reason:string}[];locked:boolean};
type Timeline={timeline:{sequence:number;event:Event}[];nodes:{id:string;kind:string;label:string}[];edges:{from:string;to:string;relation:string}[];integrity:string};

export default function ControlCenter(){
 const [section,setSection]=useState("Overview"),[data,setData]=useState<Snapshot|null>(null),[timeline,setTimeline]=useState<Timeline|null>(null),[tools,setTools]=useState<{id:string;version:string;name:string;risk:string;network:string}[]>([]),[capabilities,setCapabilities]=useState<{edges:unknown[];tokens:unknown[]}|null>(null),[error,setError]=useState("");
 const load=async()=>{try{const [c,t,tr,cr]=await Promise.all([fetch("/api/control",{cache:"no-store"}),fetch("/api/timeline",{cache:"no-store"}),fetch("/api/tools",{cache:"no-store"}),fetch("/api/capabilities",{cache:"no-store"})]);if(!c.ok)throw new Error("Control Plane unavailable");setData(await c.json());if(t.ok)setTimeline(await t.json());if(tr.ok)setTools((await tr.json()).tools);if(cr.ok)setCapabilities(await cr.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Unknown error")}};
 useEffect(()=>{load();const id=setInterval(load,2000);return()=>clearInterval(id)},[]);
 const action=async(body:object)=>{await fetch("/api/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await load()};
 const locked=Boolean(data?.locked),agents=data?.agents??[],missions=data?.missions??[],tasks=data?.tasks??[],experiments=data?.experiments??[],sandboxes=data?.sandboxes??[],events=data?.events??[],approvals=data?.approvals??[];
 const title=section==="Overview"?"Control Center":section;
 const avg=Math.round(([...agents,...tasks,...experiments].reduce((n,x)=>n+x.progress,0)/Math.max(1,[...agents,...tasks,...experiments].length)));
 return <main className="shell"><aside><div className="brand"><span>✦</span><div><b>BabajagaBoB</b><small>CONTROL CENTER</small></div></div><nav>{nav.map(x=><button key={x} onClick={()=>setSection(x)} className={section===x?"active":""}>{x}<span>›</span></button>)}</nav><div className="sideStatus"><small>SYSTEM</small><StatusBadge status={locked?"ERROR":"RUNNING"}/><p>{locked?"EMERGENCY LOCKDOWN":"Operational · control plane"}</p></div></aside>
 <section className="content"><header><div><small>PROJECT / BABAJAGABOB</small><h1>{title}</h1></div><div className="headerActions"><span className="privacy">NETWORK · DENY BY DEFAULT</span><button onClick={()=>action({action:"lockdown",locked:!locked})} className="danger">{locked?"RELEASE LOCKDOWN":"EMERGENCY LOCKDOWN"}</button></div></header>
 {error&&<div className="alert">Control Plane error: {error}</div>}{locked&&<div className="alert">Emergency lockdown active — execution is halted until explicitly released.</div>}
 {section==="Overview"?<><div className="metrics">{[{k:"Agents",v:String(agents.length).padStart(2,"0"),s:agents.filter(a=>["RUNNING","EXECUTING"].includes(a.status)).length+" active"},{k:"Progress",v:avg+"%",s:"live work"},{k:"Tasks",v:String(tasks.length).padStart(2,"0"),s:tasks.filter(t=>t.status==="RUNNING").length+" running"},{k:"Experiments",v:String(experiments.length).padStart(2,"0"),s:experiments.filter(x=>x.status==="EXPERIMENT").length+" active"},{k:"Approvals",v:String(approvals.filter(a=>a.status==="PENDING").length).padStart(2,"0"),s:"pending"}].map(x=><div className="metric" key={x.k}><small>{x.k}</small><strong>{x.v}</strong><span>{x.s}</span></div>)}</div>
 <div className="grid"><section className="panel"><div className="panelHead"><div><small>LIVE OBSERVATORY</small><h2>Agents</h2></div><span className="live">● LIVE</span></div>{agents.map(a=><div className="agent" key={a.id}><div className="avatar">{a.name[0]}</div><div className="agentMain"><div className="agentTitle"><b>{a.name}</b><span>{a.role}</span><StatusBadge status={a.status}/></div><div className="bar"><i style={{width:a.progress+"%"}}/></div><small>{a.id} · {a.task} · {a.progress}%</small></div></div>)}</section>
 <section className="panel"><div className="panelHead"><div><small>EVENT FABRIC</small><h2>Live Timeline</h2></div><button onClick={()=>action({action:"guardian"})} disabled={locked}>Guardian Check</button></div><div className="timeline">{(timeline?.timeline??events.map(e=>({sequence:0,event:e}))).slice(0,10).map(x=><div className="event" key={x.event.id}><i/><span>{x.event.message}</span><small>{x.event.time} · {x.event.causalParentId?"causal":"root"}</small></div>)}</div></section>
 <section className="panel"><div className="panelHead"><div><small>WHY / DECISION CONTEXT</small><h2>Current Work</h2></div></div>{tasks.slice(0,4).map(t=><div className="task" key={t.id}><b>{t.id}</b><span>{t.title}</span><StatusBadge status={t.status}/><small>{t.progress}% · {t.risk} · {t.requiresApproval?"approval":"delegated"}</small></div>)}</section>
 <section className="panel"><div className="panelHead"><div><small>CAUSAL FABRIC</small><h2>Replay Integrity</h2></div></div><div className="integrity"><strong>{timeline?.integrity??"loading"}</strong><span>{timeline?.nodes.length??0} nodes · {timeline?.edges.length??0} relations</span><small>Replay uses auditable events and provenance; hidden chain-of-thought is not exposed.</small></div></section></div></>:section==="Replay"?<Replay timeline={timeline}/>:<Module section={section} agents={agents} missions={missions} tasks={tasks} experiments={experiments} sandboxes={sandboxes} tools={tools} capabilities={capabilities}/>}
 <footer><span>LOCAL CONTROL PLANE</span><span>Audit: DURABLE</span><span>Secrets: BROKERED</span><span>External sharing: DISABLED</span><span>Replay: INTEGRITY-CHECKED</span></footer></section></main>
}
function Replay({timeline}:{timeline:Timeline|null}){return <section className="panel sectionPanel"><small>CAUSAL REPLAY</small><h2>Time Machine</h2><p>Chronological events with causal parents and provenance relationships.</p><div className="replay">{(timeline?.timeline??[]).map(x=><div className="replayRow" key={x.event.id}><strong>#{x.sequence}</strong><StatusBadge status={x.event.status}/><span>{x.event.message}</span><small>{x.event.actor} · {x.event.causalParentId??"ROOT"}</small></div>)}</div></section>}
function Module({section,agents,missions,tasks,experiments,sandboxes,tools,capabilities}:{section:string;agents:Agent[];missions:Mission[];tasks:Snapshot["tasks"];experiments:Experiment[];sandboxes:Sandbox[];tools:{id:string;version:string;name:string;risk:string;network:string}[];capabilities:{edges:unknown[];tokens:unknown[]}|null}){const rows=section==="Agents"?agents.map(x=>[x.id,x.name,x.status,x.progress+"%",x.task]):section==="Missions"?missions.map(x=>[x.id,x.title,x.status,x.progress+"%",x.owner]):section==="Tasks"?tasks.map(x=>[x.id,x.title,x.status,x.progress+"%",x.risk]):section==="Experiments"?experiments.map(x=>[x.id,x.title,x.status,x.progress+"%",x.knowledgeState]):section==="Sandboxes"?sandboxes.map(x=>[x.id,x.type,x.status,x.network,x.task]):section==="Security"?[[String(capabilities?.edges.length??0),"authority edges","ACTIVE",String(capabilities?.tokens.length??0),"capability tokens"]]:section==="Integrations"?tools.map(x=>[x.id,x.name,"REGISTERED",x.risk,x.network]):[[section,"module","READY","—","explicit integration boundary"]];return <section className="panel sectionPanel"><small>MODULE / {section.toUpperCase()}</small><h2>{section}</h2><p>Every operation exposes explicit state, progress, risk and integration boundaries.</p><div className="moduleTable">{rows.map((r,i)=><div className="moduleRow" key={i}>{r.map((v,j)=><span key={j} className={j===2?"state":""}>{v}</span>)}</div>)}</div></section>}
